# Site/theme
title:              Thomas J. Leeper
author:             Thomas J. Leeper
name:               Thomas J. Leeper
bio:                'Behavioral scientist and R hacker, affiliated with the London School of Economics'
description:        'Thomas J. Leeper, PhD ~ Behavioral Scientist and R Hacker'
reading_time:       true
words_per_minute:   200
logo:               'assets/img/thomas2016.jpg'
locale:             en_US
url:                https://www.thomasleeper.com

# Jekyll
permalink:          /:year/:month/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, LICENSE, Rakefile, 'ampolcourse/', 'designcourse/', 'expcourse/', 'exppolcourse/', 'lectures/', 'legexpcourse/', 'opinioncourse/', 'polpsycourse/', 'rcourse/', 'regcourse/', 'rrcourse/', 'statcompcourse/', 'surveycourse/', 'surveyexpcourse/', 'websurveycourse/']

# Social
email:              thosjleeper@gmail.com
twitter:            thosjleeper
github-url:         leeper
stackoverflow:      2338862/thomas
linkedin:           thomasjleeper
orcid:              '0000-0003-4097-6326'
dataverse:          leeper
google-scholar:     'hqiux-MAAAAJ'
publons:            '634082'

# Gems
plugins:
#  - jekyll-mentions
  - jekyll-feed
#  - jekyll-sitemap
#  - jekyll-gist
