# Site
title:              Thomas J. Leeper
author:             Thomas J. Leeper
name:               Thomas J. Leeper
bio:                '<a href="http://www.lse.ac.uk/government/whosWho/Academic%20profiles/ThomasLeeper.aspx">Associate Professor in Political Behaviour</a><br /><a href="http://www.lse.ac.uk/government/">Government Department</a><br /><a href="http://www.lse.ac.uk/">London School of Economics and Political Science</a>'
description:        'Thomas J. Leeper ~ Associate Professor in Political Behaviour, Government Department, London School of Economics and Political Science'
reading_time:       true
words_per_minute:   200
logo:               'assets/img/thomas2016.jpg'
background:         'assets/img/canterbury.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://www.thomasleeper.com

# Jekyll
permalink:          /:year/:month/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
exclude:           ['lectures/']

# Social
email:              thosjleeper@gmail.com
twitter:            thosjleeper
github-url:         leeper
stackoverflow:      2338862/thomas
linkedin:           thomasjleeper
orcid:              '0000-0003-4097-6326'
dataverse:          leeper
google-scholar:     'hqiux-MAAAAJ'
publons:            '634082'

# Gems
plugins:
#  - jekyll-mentions
  - jekyll-feed
#  - jekyll-sitemap
#  - jekyll-gist

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, LICENSE, Rakefile]
